### ISSUE TITLE
API key needed for this system

### ISSUE THREAD

**Issue by dudztroyer** [AlessandroMinoccheri/codeigniter-currency-converter#10]
Now you need to get an API key to make this system work. Can anyone take look on any workarounds or make a fix to get it working with the API key? Otherwise I'll do it in a few days when I get time.

**Comment by AlessandroMinoccheri** [comment]
If you want you can create a Pull Request about it, if you know the solution.
I'm really happy if you would like to improve this project.

Let me know if you need some help about it

**Comment by dudztroyer** [comment]
If you could do it to get it working, would be better hehe

**Comment by AlessandroMinoccheri** [comment]
Ok, could you please explain well what is your problem and I'll try to fix it.
Thanks

**Comment by dudztroyer** [comment]
The API which I've installed 8months ago on the last push has changed and now needs to have an API key to be able to use for free.

You have 2 options: make the new API compatible adding the API key on the post, or find a new API and make it compatible.

Since it is still free, i'd go for the first option.

Thanks

________________________________
De: Alessandro Minoccheri <notifications@github.com>
Enviado: terça-feira, 19 de fevereiro de 2019 13:07
Para: AlessandroMinoccheri/codeigniter-currency-converter
Cc: dudztroyer; Author
Assunto: Re: [AlessandroMinoccheri/codeigniter-currency-converter] API key needed for this system (#10)


Ok, could you please explain well what is your problem and I'll try to fix it.
Thanks

**Comment by AlessandroMinoccheri** [comment]
I have released version 1.4.0, try please an let me know if there is some problem @dudztroyer

**Comment by dudztroyer** [comment]
Did you try it?
